using System.Windows.Input;

namespace HandwritingFeedback.Util
{
    /// <summary>
    /// Class that holds input data used for real-time feedback. New fields should be created when <br />
    /// adding input sources (for example an Image field for a camera input source).
    /// </summary>
    public class RTFInputData
    {
        /// <summary>
        /// Input that is generated by a tablet with a stylus.
        /// </summary>
        public StylusPoint StylusPoint;

        /// <summary>
        /// Time at which stylus point was received.
        /// </summary>
        public long Timestamp;
    }
}
